---
- hosts: "{{ passed_in_hosts }}"
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: Install the necessary packages
      yum:
        name: "{{ package }} "
        state: present
      vars:
        package:
        - wget
        - httpd
        - php 
        - php-mysqlnd
        - php-gd 
        - php-xml 
        - mariadb-server 
        - mariadb 
        - php-mbstring
        
    - name: Install the php7.4 on the mediawiki host
      command: amazon-linux-extras install php7.4 -y
      
    - name: Start the services
      service:
        name: "{{ item }}"
        state: started
      with_items:
        - httpd
        - mariadb
         
    - name: Download the mediawiki package
      get_url:
        url: https://releases.wikimedia.org/mediawiki/1.34/mediawiki-1.34.2.tar.gz
        dest: /var/www/html
        
    - name: Extract the mediawiki archive
      command: "{{ item }}"
      with_items:
       - tar -zxf /var/www/html/mediawiki-1.34.2.tar.gz -C /var/www/html
              
    - name: Create the symlink for the mediawiki binaries
      file:
        src: /var/www/html/mediawiki-1.34.2
        dest: /var/www/html/mediawiki
        owner: apache
        group: apache
        state: link        
       
    - name: Change owenership of the mediawiki dir recurrsively
      file:
        path: /var/www/html/mediawiki-1.34.2
        state: directory
        recurse: yes
        owner: apache
        group: apache
        
    - name: Copy the db script to the remote server for execution
      copy:
        src: ./ansible_templates/mysql-db-scripts/mediawiki_db_setup.sql
        dest: /home/ec2-user
        owner: ec2-user
        group: ec2-user
        mode: '0664'
        
    - name: execute the db-script on the command line
      shell: mysql -u root < /home/ec2-user/mediawiki_db_setup.sql;
      register: script_output
      failed_when: false
      no_log: true
      ignore_errors: true
      
    #- name: Output message when the Database already exists  
    - debug: 
        msg: Database is already created
      when: script_output.rc == 1
      
        
    - name: Restart the services
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - httpd
        - mariadb